/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jarcinemas;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author asifrasheed
 */
public class AccountMenu extends javax.swing.JFrame {

    /**
     * Creates new form AccountMenu
     */
    JLabel closeButton;
    int originalwidth, originalheight;
    public AccountMenu(int width, int height) {
        initComponents();
        
        originalwidth = width;
        originalheight = height;
        
        this.setSize(width/2, height/2);
        this.setLocationRelativeTo(null);
        this.setAlwaysOnTop(true);
        
        jPanel2.setPreferredSize(new Dimension(this.getWidth(),this.getHeight()/20));
        jPanel3.setPreferredSize(new Dimension(this.getWidth(),(this.getHeight()-(this.getHeight()/20))/2));
        jPanel4.setPreferredSize(new Dimension(this.getWidth(),(this.getHeight()-(this.getHeight()/20))/2));
        
        closeButton = new JLabel("☒",SwingConstants.RIGHT);
        closeButton.setFont(new Font("Lucida Grande",Font.BOLD,24));
        closeButton.setForeground(new Color(255,51,51));
        closeButton.addMouseMotionListener(new MouseMotionAdapter(){
            public void mouseEntered(MouseEvent evt){
                closeButton.setForeground(new Color(153,153,153));
            }
            public void mouseExited(MouseEvent evt){
                closeButton.setForeground(new Color(255,51,51));
            }
        });
        closeButton.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent evt){
                (new Home()).setVisible(true);
                dispose();
            }
        });
        jPanel2.add(closeButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Bookings = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Settings = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        Bookings.setBackground(new java.awt.Color(255, 51, 51));
        Bookings.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Bookings.setForeground(new java.awt.Color(153, 153, 153));
        Bookings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bookings.setText("My Bookings");
        Bookings.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        Bookings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookingsMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BookingsMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BookingsMouseEntered(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 132;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(51, 90, 52, 90);
        jPanel3.add(Bookings, gridBagConstraints);

        getContentPane().add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        Settings.setBackground(new java.awt.Color(255, 51, 51));
        Settings.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Settings.setForeground(new java.awt.Color(153, 153, 153));
        Settings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Settings.setText("Account Settings");
        Settings.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        Settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingsMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SettingsMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SettingsMouseEntered(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 166;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(51, 0, 52, 0);
        jPanel4.add(Settings, gridBagConstraints);

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private int clickx, clicky;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen()-clickx;
        int y = evt.getYOnScreen()-clicky;
        this.setLocation(x, y);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        clickx = evt.getX();
        clicky = evt.getY();
        setCursor(new Cursor(Cursor.MOVE_CURSOR));
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_formMouseReleased

    private void BookingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingsMouseClicked
        try {
            // TODO add your handling code here:
            SQLConnect databse = new SQLConnect();
            if(!databse.executeQuery("select * from booking where username='"+(new UserInfo()).username()+"'"))
                (new popup((new Home()),"There are no existing booking under this name!")).setVisible(true);
            else{
                (new Bookings(originalwidth,originalheight)).setVisible(true);
                this.dispose();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AccountMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AccountMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BookingsMouseClicked

    private void BookingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingsMouseExited
        // TODO add your handling code here:
        Bookings.setOpaque(false);
        Bookings.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_BookingsMouseExited

    private void BookingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingsMouseEntered
        // TODO add your handling code here:
        Bookings.setOpaque(true);
        Bookings.setForeground(Color.WHITE);
    }//GEN-LAST:event_BookingsMouseEntered

    private void SettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseClicked
        // TODO add your handling code here:
        (new AccountSettings(originalwidth,originalheight)).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SettingsMouseClicked

    private void SettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseExited
        // TODO add your handling code here:
        Settings.setOpaque(false);
        Settings.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_SettingsMouseExited

    private void SettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseEntered
        // TODO add your handling code here:
        Settings.setOpaque(true);
        Settings.setForeground(Color.WHITE);
    }//GEN-LAST:event_SettingsMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AccountMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bookings;
    private javax.swing.JLabel Settings;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
