/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jarcinemas;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import static java.lang.System.exit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author asifrasheed
 */
public class JarCinemas extends javax.swing.JFrame {
    SQLConnect database;
    ResultSet data;
    /**
     * Creates new form JarCinemas
     */
    public JarCinemas() {
        initComponents();
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(3*screen.width/4, 3*screen.height/4);
        this.setLocationRelativeTo(null);
        toggleLogin();
        loginTitle.requestFocusInWindow();
        passwordLogin.setEchoChar((char)0);
        passwordSignup.setEchoChar((char)0);
        try {
            database = new SQLConnect();
        } catch (ClassNotFoundException ex) {
            (new popup(this,"JDBC driver missing")).setVisible(true);
            return;
        } catch (SQLException ex) {
            (new popup(this,"Error establishing database connection")).setVisible(true);
            return;
        }
        
        try {
            data = database.getResultSet("SELECT * FROM loginusers");
        } catch (SQLException ex) {
            (new popup(this,"Error retrieving user data")).setVisible(true);
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        contentPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        formContainer = new javax.swing.JPanel();
        loginForm = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        loginTitle = new javax.swing.JLabel();
        usernameLogin = new javax.swing.JTextField();
        loginButton = new javax.swing.JLabel();
        signupMessage1 = new javax.swing.JLabel();
        signupMessage2 = new javax.swing.JLabel();
        passwordLogin = new javax.swing.JPasswordField();
        signupPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        loginTitle1 = new javax.swing.JLabel();
        nameSignup = new javax.swing.JTextField();
        signupButton = new javax.swing.JLabel();
        loginMessage1 = new javax.swing.JLabel();
        loginMessage2 = new javax.swing.JLabel();
        usernameSignup = new javax.swing.JTextField();
        passwordSignup = new javax.swing.JPasswordField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JarCinemas");
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        contentPanel.setBackground(new java.awt.Color(0, 0, 0));
        contentPanel.setLayout(new java.awt.GridBagLayout());

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jarcinemas/Revenge (undated).jpg"))); // NOI18N
        jPanel3.add(jLabel4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        contentPanel.add(jPanel3, gridBagConstraints);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jarcinemas/Screen Shot 2020-04-05 at 8.39.47 PM.png"))); // NOI18N
        jPanel4.add(jLabel5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        contentPanel.add(jPanel4, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText("lkkkkk");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        contentPanel.add(jLabel3, gridBagConstraints);

        getContentPane().add(contentPanel);

        formPanel.setBackground(new java.awt.Color(255, 255, 255));
        formPanel.setLayout(new java.awt.GridBagLayout());

        formContainer.setLayout(new java.awt.CardLayout());

        loginForm.setBackground(new java.awt.Color(255, 255, 255));
        loginForm.setLayout(new java.awt.CardLayout());

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("☒");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });

        loginTitle.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        loginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginTitle.setText("Log In");

        usernameLogin.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        usernameLogin.setForeground(new java.awt.Color(153, 153, 153));
        usernameLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameLogin.setText("username");
        usernameLogin.setToolTipText("");
        usernameLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        usernameLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameLoginFocusLost(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(255, 51, 51));
        loginButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(153, 153, 153));
        loginButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginButton.setText("Log In");
        loginButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginButtonMouseEntered(evt);
            }
        });

        signupMessage1.setText("Don't have an account?");

        signupMessage2.setForeground(new java.awt.Color(255, 51, 51));
        signupMessage2.setText("Sign Up");
        signupMessage2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMessage2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signupMessage2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signupMessage2MouseEntered(evt);
            }
        });

        passwordLogin.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        passwordLogin.setForeground(new java.awt.Color(153, 153, 153));
        passwordLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordLogin.setText("password");
        passwordLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        passwordLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordLoginFocusLost(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(signupMessage1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(signupMessage2))
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(usernameLogin)
                                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passwordLogin)))
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(92, 92, 92)
                .addComponent(loginTitle)
                .addGap(98, 98, 98)
                .addComponent(usernameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signupMessage1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signupMessage2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(313, Short.MAX_VALUE))
        );

        loginForm.add(loginPanel, "card2");

        signupPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("☒");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });

        loginTitle1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        loginTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginTitle1.setText("Sign Up");

        nameSignup.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        nameSignup.setForeground(new java.awt.Color(153, 153, 153));
        nameSignup.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameSignup.setText("Your Name");
        nameSignup.setToolTipText("");
        nameSignup.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        nameSignup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameSignupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameSignupFocusLost(evt);
            }
        });

        signupButton.setBackground(new java.awt.Color(255, 51, 51));
        signupButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        signupButton.setForeground(new java.awt.Color(153, 153, 153));
        signupButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signupButton.setText("Sign Up");
        signupButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        signupButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signupButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signupButtonMouseEntered(evt);
            }
        });

        loginMessage1.setText("Already have an account?");

        loginMessage2.setForeground(new java.awt.Color(255, 51, 51));
        loginMessage2.setText("Log In");
        loginMessage2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMessage2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMessage2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMessage2MouseEntered(evt);
            }
        });

        usernameSignup.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        usernameSignup.setForeground(new java.awt.Color(153, 153, 153));
        usernameSignup.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameSignup.setText("Preffered Username");
        usernameSignup.setToolTipText("");
        usernameSignup.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        usernameSignup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameSignupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameSignupFocusLost(evt);
            }
        });

        passwordSignup.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        passwordSignup.setForeground(new java.awt.Color(153, 153, 153));
        passwordSignup.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordSignup.setText("Your Password");
        passwordSignup.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        passwordSignup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordSignupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordSignupFocusLost(evt);
            }
        });

        javax.swing.GroupLayout signupPanelLayout = new javax.swing.GroupLayout(signupPanel);
        signupPanel.setLayout(signupPanelLayout);
        signupPanelLayout.setHorizontalGroup(
            signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signupPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(signupPanelLayout.createSequentialGroup()
                                .addComponent(loginMessage1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loginMessage2))
                            .addComponent(nameSignup)
                            .addComponent(signupButton, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(usernameSignup)
                            .addComponent(passwordSignup))
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signupPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        signupPanelLayout.setVerticalGroup(
            signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(92, 92, 92)
                .addComponent(loginTitle1)
                .addGap(72, 72, 72)
                .addComponent(nameSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usernameSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginMessage1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginMessage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(166, 166, 166))
        );

        loginForm.add(signupPanel, "card2");

        formContainer.add(loginForm, "card2");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 77;
        gridBagConstraints.ipady = 183;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(formContainer, gridBagConstraints);

        getContentPane().add(formPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked
    private Color defaultClose = new java.awt.Color(255, 51, 51);
    private Color secondaryClose = new java.awt.Color(153, 153, 153);
    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
       jLabel1.setForeground(secondaryClose);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jLabel1.setForeground(defaultClose);
    }//GEN-LAST:event_jLabel1MouseExited
    private int clickx, clicky;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen()-clickx;
        int y = evt.getYOnScreen()-clicky;
        this.setLocation(x, y);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        clickx = evt.getX();
        clicky = evt.getY();
        setCursor(new Cursor(Cursor.MOVE_CURSOR));
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_formMouseReleased

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
        defaultClose = new java.awt.Color(255, 255, 255);
        secondaryClose = new java.awt.Color(255, 51, 51);
        jLabel1.setForeground(defaultClose);
    }//GEN-LAST:event_formFocusLost

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        defaultClose = new java.awt.Color(255, 51, 51);
        secondaryClose = new java.awt.Color(153, 153, 153);
        jLabel1.setForeground(defaultClose);
    }//GEN-LAST:event_formFocusGained

    private void usernameLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameLoginFocusGained
        // TODO add your handling code here:
        usernameLogin.setText("");
        usernameLogin.setForeground(Color.BLACK);
    }//GEN-LAST:event_usernameLoginFocusGained

    private void usernameLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameLoginFocusLost
        // TODO add your handling code here:
        if(usernameLogin.getText().equals("")){
            usernameLogin.setText("username");
            usernameLogin.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_usernameLoginFocusLost

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        jLabel3.requestFocusInWindow();
    }//GEN-LAST:event_formMouseClicked

    private void loginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseEntered
        // TODO add your handling code here:
        loginButton.setOpaque(true);
        loginButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_loginButtonMouseEntered

    private void loginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseExited
        // TODO add your handling code here:
        loginButton.setOpaque(false);
        loginButton.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_loginButtonMouseExited

    private void signupMessage2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMessage2MouseEntered
        // TODO add your handling code here:
        signupMessage2.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_signupMessage2MouseEntered

    private void signupMessage2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMessage2MouseExited
        // TODO add your handling code here:
        signupMessage2.setForeground(new Color(255,51,51));
    }//GEN-LAST:event_signupMessage2MouseExited

    private void signupMessage2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMessage2MouseClicked
        // TODO add your handling code here:
        toggleSignup();
    }//GEN-LAST:event_signupMessage2MouseClicked

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        // TODO add your handling code here:
        try {
            data.beforeFirst();
            boolean isValid = database.executeQuery("select * from loginusers where username='"+usernameLogin.getText()+"' and password='"+String.valueOf(passwordLogin.getPassword())+"'");
            if(isValid){
                ResultSet rs = database.getResultSet("select * from loginusers where username='"+usernameLogin.getText()+"'");
                rs.next();
                UserInfo user = new UserInfo(rs.getString("name"),usernameLogin.getText(),rs.getInt("type"));
                (new Home()).setVisible(true);
                this.dispose();
            }
            else (new popup(this,"Invalid username or password")).setVisible(true);
        } catch (SQLException ex) {
            (new popup(this,ex.getMessage())).setVisible(true);
        }
        usernameLogin.setText("username");
        usernameLogin.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_loginButtonMouseClicked

    private void nameSignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameSignupFocusGained
        // TODO add your handling code here:
        nameSignup.setText("");
        nameSignup.setForeground(Color.BLACK);
    }//GEN-LAST:event_nameSignupFocusGained

    private void nameSignupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameSignupFocusLost
        // TODO add your handling code here:
        if(nameSignup.getText().equals("")){
            nameSignup.setText("Your Name");
            nameSignup.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_nameSignupFocusLost

    private void signupButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupButtonMouseClicked
        try {
            boolean isValid = false;
            data.beforeFirst();
            while(data.next()){
                if(data.getString("username").equals(usernameSignup.getText()))
                    isValid = true;
            }
            if(String.valueOf(passwordSignup.getPassword()).length()<7||nameSignup.getText().length()==0||String.valueOf(passwordSignup.getPassword()).equals("Your Name")||nameSignup.getText().equals("Your Password")
                    ||usernameSignup.getText().equals("Preffered Username")||usernameSignup.getText().length()==0)
                isValid = true;
            // TODO add your handling code here:
            if(!isValid && database.executeQuery("INSERT INTO loginusers VALUES ('"+usernameSignup.getText()+"','"+String.valueOf(passwordSignup.getPassword())+"','"+nameSignup.getText()+"',1)")){
                {
                    (new popup(this,"Successfully registered your account")).setVisible(true);
                    toggleLogin();
                }
                try {
                    data = database.getResultSet("SELECT * FROM loginusers");
                } catch (SQLException ex) {
                    (new popup(this,"Error retrieving user data")).setVisible(true);
                    return;
                }
            }
            else
                (new popup(this,"Failed to register your account")).setVisible(true);
                } catch (SQLException ex) {
            Logger.getLogger(JarCinemas.class.getName()).log(Level.SEVERE, null, ex);
        }
        usernameSignup.setText("Preffered Username");
        usernameSignup.setForeground(new Color(153,153,153));
        
        passwordSignup.setEchoChar((char)0);
        passwordSignup.setForeground(new Color(153,153,153));
        passwordSignup.setText("Your Password");
        
        nameSignup.setText("Your Name");
        nameSignup.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_signupButtonMouseClicked

    private void signupButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupButtonMouseExited
        // TODO add your handling code here:
        signupButton.setOpaque(false);
        signupButton.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_signupButtonMouseExited

    private void signupButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupButtonMouseEntered
        // TODO add your handling code here:
        signupButton.setOpaque(true);
        signupButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_signupButtonMouseEntered

    private void loginMessage2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMessage2MouseClicked
        // TODO add your handling code here:
        toggleLogin();
    }//GEN-LAST:event_loginMessage2MouseClicked

    private void loginMessage2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMessage2MouseExited
        // TODO add your handling code here:
        loginMessage2.setForeground(new Color(255,51,51));
    }//GEN-LAST:event_loginMessage2MouseExited

    private void loginMessage2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMessage2MouseEntered
        // TODO add your handling code here:
        loginMessage2.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_loginMessage2MouseEntered

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        jLabel2.setForeground(defaultClose);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        jLabel2.setForeground(secondaryClose);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void usernameSignupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameSignupFocusLost
        // TODO add your handling code here:
        if(usernameSignup.getText().equals("")){
            usernameSignup.setText("Preffered Username");
            usernameSignup.setForeground(new Color(153,153,153));
        }
        else{
            if(usernameSignup.getText().contains(" ")){
                javax.swing.JFrame ref = this;
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        (new popup(ref,"Your username should be a single word")).setVisible(true);
                    }
                });
                usernameSignup.requestFocus();
                return;
            }
        }
    }//GEN-LAST:event_usernameSignupFocusLost

    private void usernameSignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameSignupFocusGained
        // TODO add your handling code here:
        usernameSignup.setText("");
        usernameSignup.setForeground(Color.BLACK);
    }//GEN-LAST:event_usernameSignupFocusGained

    private void passwordLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordLoginFocusGained
        // TODO add your handling code here:
        passwordLogin.setEchoChar('•');
        passwordLogin.setText("");
        passwordLogin.setForeground(Color.BLACK);
    }//GEN-LAST:event_passwordLoginFocusGained

    private void passwordLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordLoginFocusLost
        // TODO add your handling code here:
        if(String.valueOf(passwordLogin.getPassword()).equals("")){
            passwordLogin.setEchoChar((char)0);
            passwordLogin.setForeground(new Color(153,153,153));
            passwordLogin.setText("password");
        }
    }//GEN-LAST:event_passwordLoginFocusLost

    private void passwordSignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordSignupFocusGained
        // TODO add your handling code here:
        passwordSignup.setText("");
        passwordSignup.setEchoChar('•');
        passwordSignup.setForeground(Color.BLACK);
    }//GEN-LAST:event_passwordSignupFocusGained

    private void passwordSignupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordSignupFocusLost
        // TODO add your handling code here:
        if(String.valueOf(passwordSignup.getPassword()).equals("")){
            passwordSignup.setText("Your Password");
            passwordSignup.setEchoChar((char)0);
            passwordSignup.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_passwordSignupFocusLost

    private void setLoginVisible(boolean visible){
        loginPanel.setVisible(visible);
    }

    private void setSignupVisible(boolean visible){
        signupPanel.setVisible(visible);
    }

    /**
     * Toggles to login
     */
    private void toggleLogin(){
        setLoginVisible(true);
        setSignupVisible(false);
    }

    /**
     * Toggles to sign up
     */
    private void toggleSignup(){
        setLoginVisible(false);
        setSignupVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JarCinemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JarCinemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JarCinemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JarCinemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel("com.apple.laf.AquaLookAndFeel");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(JarCinemas.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(JarCinemas.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(JarCinemas.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(JarCinemas.class.getName()).log(Level.SEVERE, null, ex);
                }
                new JarCinemas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel formContainer;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel loginButton;
    private javax.swing.JPanel loginForm;
    private javax.swing.JLabel loginMessage1;
    private javax.swing.JLabel loginMessage2;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel loginTitle;
    private javax.swing.JLabel loginTitle1;
    private javax.swing.JTextField nameSignup;
    private javax.swing.JPasswordField passwordLogin;
    private javax.swing.JPasswordField passwordSignup;
    private javax.swing.JLabel signupButton;
    private javax.swing.JLabel signupMessage1;
    private javax.swing.JLabel signupMessage2;
    private javax.swing.JPanel signupPanel;
    private javax.swing.JTextField usernameLogin;
    private javax.swing.JTextField usernameSignup;
    // End of variables declaration//GEN-END:variables
}
