/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jarcinemas;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author asifrasheed
 */
public class ManageMovies extends javax.swing.JFrame {

    /**
     * Creates new form ManageMovies
     */
    public ManageMovies() {
        initComponents();
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screen.width/4, screen.height/4);
        this.setLocationRelativeTo(null);
        
        jPanel2.setPreferredSize(new Dimension(this.getWidth(),this.getHeight()/15));
        jPanel3.setPreferredSize(new Dimension(this.getWidth(),(this.getHeight()-(this.getHeight()/15))/2));
        jPanel4.setPreferredSize(new Dimension(this.getWidth(),(this.getHeight()-(this.getHeight()/15))/2));
        
        JLabel closeButton = new JLabel("☒",SwingConstants.RIGHT);
        closeButton.setFont(new Font("Lucida Grande",Font.BOLD,24));
        closeButton.setForeground(new Color(255,51,51));
        closeButton.addMouseMotionListener(new MouseMotionAdapter(){
            public void mouseEntered(MouseEvent evt){
                closeButton.setForeground(new Color(153,153,153));
            }
            public void mouseExited(MouseEvent evt){
                closeButton.setForeground(new Color(255,51,51));
            }
        });
        closeButton.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent evt){
                (new Home()).setVisible(true);
                dispose();
            }
        });
        jPanel2.add(closeButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        addMovie = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        manageMovies = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout());
        getContentPane().add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        addMovie.setBackground(new java.awt.Color(255, 51, 51));
        addMovie.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        addMovie.setForeground(new java.awt.Color(153, 153, 153));
        addMovie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addMovie.setText("Add Movie");
        addMovie.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        addMovie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMovieMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMovieMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMovieMouseEntered(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 132;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(51, 90, 52, 90);
        jPanel3.add(addMovie, gridBagConstraints);

        getContentPane().add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        manageMovies.setBackground(new java.awt.Color(255, 51, 51));
        manageMovies.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        manageMovies.setForeground(new java.awt.Color(153, 153, 153));
        manageMovies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageMovies.setText("Manage Movies");
        manageMovies.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        manageMovies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageMoviesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageMoviesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageMoviesMouseEntered(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 166;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(51, 0, 52, 0);
        jPanel4.add(manageMovies, gridBagConstraints);

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMovieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMovieMouseClicked
        (new AddMovie()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addMovieMouseClicked

    private void addMovieMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMovieMouseExited
        // TODO add your handling code here:
        addMovie.setOpaque(false);
        addMovie.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_addMovieMouseExited

    private void addMovieMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMovieMouseEntered
        // TODO add your handling code here:
        addMovie.setOpaque(true);
        addMovie.setForeground(Color.WHITE);
    }//GEN-LAST:event_addMovieMouseEntered

    private void manageMoviesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageMoviesMouseClicked
        // TODO add your handling code here:
        (new ManageExistingMovies()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manageMoviesMouseClicked

    private void manageMoviesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageMoviesMouseExited
        // TODO add your handling code here:
        manageMovies.setOpaque(false);
        manageMovies.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_manageMoviesMouseExited

    private void manageMoviesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageMoviesMouseEntered
        // TODO add your handling code here:
        manageMovies.setOpaque(true);
        manageMovies.setForeground(Color.WHITE);
    }//GEN-LAST:event_manageMoviesMouseEntered
    private int clickx, clicky;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen()-clickx;
        int y = evt.getYOnScreen()-clicky;
        this.setLocation(x, y);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        clickx = evt.getX();
        clicky = evt.getY();
        setCursor(new Cursor(Cursor.MOVE_CURSOR));
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_formMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageMovies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addMovie;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel manageMovies;
    // End of variables declaration//GEN-END:variables
}
